---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "50%"
)
```

# HCR

<!-- badges: start -->
<!-- badges: end -->

Code for implementing Hydrologic Connectivity to Rivers.

## Installation

You can install the development version of HCR from [GitHub](https://github.com/) with:

``` r
# install.packages("pak")
pak::pak("khondula/HCR")
```

## Example

This is a basic example to calculate HCR. Three examples of input datasets are included

```{r example}
library(HCR)
klamath_img_path <- system.file("extdata", "2017-01-12_S3A_tsm-Klamath.tif", package = "HCR")
klamath_sea_path <- system.file("extdata", "sea_pt-Klamath.geojson", package = "HCR")
klamath_land_path <- system.file("extdata", "river_pts-Klamath.geojson", package = "HCR")

klamath_out <- run_hcr(input_tif = klamath_img_path,
        sea_point = klamath_sea_path,
        land_points = klamath_land_path,
        land_points_id_col = 'pourpoint_id',
        output_dir = 'klamath_out')

russian_img_path <- system.file("extdata", "2019-03-29_S3B_tsm-Russian.tif", package = "HCR")
russian_sea_path <- system.file("extdata", "sea_pt-Russian.geojson", package = "HCR")
russian_land_path <- system.file("extdata", "river_pts-Russian.geojson", package = "HCR")

russian_out <- run_hcr(input_tif = russian_img_path,
        sea_point = russian_sea_path,
        land_points = russian_land_path,
        land_points_id_col = 'pourpoint_id',
        output_dir = 'russian_out')

navarro_img_path <- system.file("extdata", "2016-12-16_S3A_tsm-Navarro.tif", package = "HCR")
navarro_sea_path <- system.file("extdata", "sea_pt-Navarro.geojson", package = "HCR")
navarro_land_path <- system.file("extdata", "river_pts-Navarro.geojson", package = "HCR")

navarro_out <- run_hcr(input_tif = navarro_img_path,
        sea_point = navarro_sea_path,
        land_points = navarro_land_path,
        land_points_id_col = 'pourpoint_id',
        output_dir = 'russian_out')
```
