#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom colorspace divergingx_hcl
#' @importFrom colorspace scale_color_continuous_divergingx
#' @importFrom colorspace scale_fill_continuous_divergingx
#' @importFrom dplyr arrange
#' @importFrom dplyr bind_cols
#' @importFrom dplyr distinct
#' @importFrom dplyr filter
#' @importFrom dplyr if_all
#' @importFrom dplyr left_join
#' @importFrom dplyr mutate
#' @importFrom dplyr rename
#' @importFrom dplyr select
#' @importFrom FNN get.knnx
#' @importFrom fs dir_create
#' @importFrom gdistance costDistance
#' @importFrom gdistance geoCorrection
#' @importFrom gdistance shortestPath
#' @importFrom gdistance transition
#' @importFrom ggplot2 aes
#' @importFrom ggplot2 geom_line
#' @importFrom ggplot2 geom_point
#' @importFrom ggplot2 geom_text
#' @importFrom ggplot2 ggplot
#' @importFrom ggplot2 ggsave
#' @importFrom ggplot2 labs
#' @importFrom ggplot2 theme
#' @importFrom ggplot2 theme_bw
#' @importFrom ggplot2 xlab
#' @importFrom glue glue
#' @importFrom grDevices dev.off png
#' @importFrom Kendall MannKendall
#' @importFrom methods as
#' @importFrom purrr map2
#' @importFrom raster values
#' @importFrom raster xyFromCell
#' @importFrom readr parse_number
#' @importFrom readr write_csv
#' @importFrom rlang .data
#' @importFrom scales col_numeric
#' @importFrom scico scico
#' @importFrom sf st_buffer
#' @importFrom sf st_cast
#' @importFrom sf st_coordinates
#' @importFrom sf st_length
#' @importFrom sf st_line_sample
#' @importFrom sf st_transform
#' @importFrom sf st_write
#' @importFrom terra crs
#' @importFrom terra distance
#' @importFrom terra extract
#' @importFrom terra intersect
#' @importFrom terra project
#' @importFrom terra rast
#' @importFrom terra setValues
#' @importFrom terra values
#' @importFrom terra vect
#' @importFrom tibble as_tibble
#' @importFrom tibble rowid_to_column
#' @importFrom tibble tibble
#' @importFrom tidyselect all_of
#' @importFrom tools file_path_sans_ext
#' @importFrom utils head
#' @importFrom utils head tail
#' @importFrom utils tail
## usethis namespace: end
NULL
